theme: jekyll-theme-cayman
#theme: jekyll-theme-slate
title: toio SDK for Unity
description: toio SDK for Unity document pages.
url: https://mrkksen.github.io/toio-sdk-for-unity/
plugins:
  - jekyll-seo-tag
# google_analytics: UA-133660753-6

defaults:
  - 
    scope:
      path: "" # 全てのファイルに対して適用する
    values:
      layout: "default" # デフォルトのレイアウトを指定
